### ISSUE TITLE
"Elements not tagged"?

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/graph-ryder-dashboard#3]
The Elements not tagged view is at best a misnomer, and I don't get what it actually does. It seems a list of all topics, tagged or not. I don't see a way to filter for the untagged ones. @luca can you remind me what this is for?

**Comment by luca** [comment]
This was a subview, linked from the settings page, that opened in a popup.
It seemed too cramped to stay in a small popup, and it felt it belonged in the main menu rather than hidden away in a sub-page, therefore it was promoted to the sidebar.

What it does is getting data from `[api URL base]/content/nottagged`  and then shows the lists of posts and comments.

**Comment by albertocottica** [comment]
I stand corrected. I am not convinced this view should be here (more of an Open Ethno kind of thing), but at least it has no error. Stand by while I ask Amelia what I should do.

**Comment by albertocottica** [comment]
Leave it.
